version: 2.1

executors:
    director:
        # set up the docker environment
        docker:
            - image: circleci/python:latest # Use the latest python docker.
        # set working directory
        # working_directory: /tmp

jobs:
    setup:
        executor: director
        
        steps:
            # Checkout source files:
            - checkout 
            # create cache for python dependencies:
            - restore_cache:
                key: my_dependencies
            # unstall tar and untar for chache management:
            - run: sudo install tar untar
            # Grant access to dependency locations:
            - run: sudo chown -R circleci:circleci /usr/local/bin
            - run: sudo chown -R circleci:circleci /usr/local/lib/python3.*/site-packages
            # Instalation of the required packages:
            - run:
                name: Install pandoc
                command: pip install pandoc --user
            - run:
                name: Install radon
                command: pip install radon --user
            - run:
                name: Install matplotlib
                command: pip install matplotlib --user
            - run:
                name: Install jupyter
                command: pip install jupyter --user
            - run:
                name: Install notebook converter
                command: pip install nbconvert --user
            - save_cache:
                key: my_dependencies
                paths:
                    - "/usr/local/bin"
                    - "/usr/local/lib/python3.6/site-packages"

    auto-export:
        # Define executor:
        executor: director
        
        steps:
             # load cache:
            - restore_cache:
                key: my_dependencies 
            # Create file to serve as workspace:
            - run: mkdir -p workspace
            # Export the .ipynb files to .py:
            - run:
                name: Notebook to scripts
                command: jupyter nbconvert *.ipynb --to script
            # Dependencies:
            - persist_to_workspace:
                root: workspace
                paths:
                    - test.py
                    - solution.py
                    - objectsTest.py
                    - Objects.py

    auto-test:
        # Define executor:
        executor: director
        
        steps:
            # load cache:
            - restore_cache:
                key: my_dependencies        
            - attach_workspace:
                at: /workspace
            - run:
                name: Unit_testing
                command: python test.py
            - run:
                name: Object oriented unit_testing
                command: python objectsTest.py    
  
    auto-radon:
        # Define executor:
        executor: director

        steps:
            # load cache:
            - restore_cache:
                key: my_dependencies 
            - attach_workspace:
                at: /workspace
            # Cyclomatic complexity
            - run:
                name: Cyclomatic complexity
                command: radon cc solution.py
            - run:
                name: Cyclomatic complexity OOP
                command: radon cc Objects.py
            # Halstead complexity:
            - run:
                name: Halstead complexity
                command: radon hal solution.py
            - run:
                name: Halstead complexity OOP
                command: radon hal Objects.py


workflows:
  version: 2
  my_workflow:
    jobs:
        - setup
        - auto-export:
            requires:
                - setup
        - auto-test:
            requires:
                - setup
                - auto-export
        - auto-radon:
            requires:
                - setup
                - auto-export